services:
  satisfactory-server:
    container_name: 'satisfactory-server'
    hostname: 'satisfactory-server'
    image: 'wolveix/satisfactory-server:latest'
    ports:
      - '7777:7777/udp'
      - '7777:7777/tcp'
    volumes:
      - '/home/debian/satisfactory-server:/config'
    environment:
      - MAXPLAYERS=2
      - PGID=1000
      - PUID=1000
      - STEAMBETA=experimental
    
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 4G